apiVersion: 1

datasources:
  - name: PUQ Prometheus
    type: prometheus
    uid: puq-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      exemplarTraceIdDestinations: []
